### PR TITLE
fix round in adder

### PR DESCRIPTION
**Pull request by proukornew**

### CODE REVIEW

**Comment by dawsonjon** [comment]
Thanks for your interest in this project and for taking the time to submit this pull request!

I don't think the change you have submitted is correct, it doesn't match the behaviour of the C++ model, and it causes the unit tests to fail. The intended behaviour is to check whether the value is more than half way to the next number using the guard round a sticky bits, and if so we round up by adding 1 to the mantissa. The corner case is when incrementing the mantissa would cause it to overflow to 0. In this case, we would need to increment the exponent too.

**Comment by proukornew** [comment]
Fixed. Your explanation is correct, but code is not.
1. We should check overflow and +1 exp.
2. then we add +1 to mantissa.
In your code u have reg with  2^(exp)*1.24'hfffffe turned to  
 2^(exp+1)*1.24'hffffff

**Comment by dawsonjon** [comment]
Thanks, I can understand your thinking now. I think you might have missed that `z_m <= z_m + 1` is a non-blocking assignment. When the if statement is evaluated, z_m still has its original value. So in your example, 2^(exp)*1.24'hfffffe the exponent wouldn't be incremented. Your change does pass the tests now, but it gives the same result that the original code did. I don't think this change makes any difference to the behaviour of the code.

**Comment by proukornew** [comment]
Thx. 1 question: Is it good fpu's design with states/ state reg?

**Pull request closed without merging**
